input:
  mqtt:
    urls: [tcp://otv2-mpm-mosquitto.opentwinsv2-test2.svc.cluster.local:1883]
    topics: [telemetry/#]
    client_id: benthos-mqtt-client-edge

pipeline:
  processors:
    - bloblang: |
        let topic_parts = metadata("mqtt_topic").split("/")
        let device = $topic_parts.index(-1)
        root = {
            "specversion": "1.0",
            "id": uuid_v4(),
            "source": "mqtt://sensor",
            "type": "mqtt:changes_" + $device,
            "time": now(),
            "datacontenttype": "application/json",
            "data": this
        }

output:
  kafka:
    addresses:
      - otv2-mpm-kafka-controller-0.otv2-mpm-kafka-controller-headless.opentwinsv2-test2.svc.cluster.local:9092
    topic: opentwinsv2.events
    client_id: benthos-kafka-producer
    max_in_flight: 64